### ISSUE TITLE
Adapter Setup

### ISSUE THREAD

**Issue by Saboti** [jbeenenga/ioBroker.heizungssteuerung#16]
`To use the adapter you have to add rooms to rooms enum and add the sensors and engines to the rooms. Furthermore you have to add the functions temperature, humidity and engine to the correct states. The enums will be created after the first start of the Adapter. If you have no humidity sensor you can leave it empty.`

Hi jbeenenga,
thank you for this Adapter. I like to try it out but don't get the Setup right.
I already added rooms to the room enum and added my zigbee thermostats into the rooms.
"Furthermore you have to add the functions temperature, humidity and engine to the correct states." I tried to add a single state to the e.g. enum.functions.engine or the enum.functions.temperature.
But it always tells me "Temperature sensor for room sleeping_area not found".

Any Help? Thank you!
Regards Saboti

**Comment by jbeenenga** [comment]
Hi saboti,

I'm sorry about the delay of my answer.
After my vacation I will improve the readme.

For your ask, every temperature Sensor has to be added to a room and as function temperature like this ![Screenshot.jpg](https://user-images.githubusercontent.com/19516774/202849774-cab5cd56-e388-48bd-a011-c17b2ca9ca90.jpg)

If you have any questions or problems just inform me :)

Have a nice day

**Comment by jbeenenga** [comment]
I've added a screenshot to the readme. If you need more details let me know, so I will add these to the readme
