### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [jbeenenga/ioBroker.heizungssteuerung#53]
## ioBroker adapter checker for npm access

Access right check for adapter heizungssteuerung returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.heizungssteuerung"

Current maintainers are 
    jbeenenga <j.beenenga@gmail.com>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by jbeenenga** [comment]
Hi,

bluefox was alread invited. I've send a new request, please check to make sure, that now it is correct.

Thanks
